Robots:
- robot_name: "jackal"
  description: "Clearpath Jackal mobile skid-steer platform"
  reliability: 0.8
  urdf:
    package_name: "jackal_description"
    executable: "urdf/jackal.urdf.xacro"
  navigation:
    controller:
      package_name: "jackal_tws"
      executable: "jackal_controller.launch"
      global_planner: "navfn/NavfnROS"
      local_planner: "dwa_local_planner/DWAPlannerROS"
    driver:
      package_name: "jackal_tws"
      executable: "jackal_driver.launch"
      odom_topic: "jackal_velocity_controller/odom"
      cmd_vel_topic: "jackal_velocity_controller/cmd_vel"
      cmd_vel_mux: "cmd_vel_stabilizer"